//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.AppData
{
    using System;
    using System.Collections.Generic;

    public partial class Order
    {
        public string CardNumber { get; set; }
        public string ExpDate { get; set; }
        public string CVN { get; set; }
        public string Status { get; set; }
        public System.DateTime Date { get; set; }
        public int ID { get; set; }
        public int ProductID { get; set; }
        public int UserID { get; set; }


        public Order()
        {
            CardNumber = string.Empty;
            ExpDate = string.Empty;
            CVN = string.Empty;
            Status = string.Empty;
            Date = new DateTime();
            Date = DateTime.Now;
        }

        public Order(string cardNumber, string expDate, string cvn, string status, int userId, int Id, int productId)
        {
            CardNumber = cardNumber;
            ExpDate = expDate;
            CVN = cvn;
            Status = status;
            Date = new DateTime();
            Date = DateTime.Now;
            UserID = userId;
            ID = Id;
            ProductID = productId;
        }

        public Order Clone()
        {
            Order res = new Order();
            res.CardNumber = (string)CardNumber.Clone();
            res.ExpDate = (string)ExpDate.Clone();
            res.CVN = (string)CVN.Clone();
            res.Status = (string)Status.Clone();
            res.Date = Date;
            res.UserID = UserID;
            res.ID = ID;
            res.ProductID = ProductID;
            return res;
        }
    }
}
