//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public string CardNumber { get; set; }
        public string ExpDate { get; set; }
        public string CVN { get; set; }
        public string Status { get; set; }
        public System.DateTime Date { get; set; }
        public string User { get; set; }
        public int ID { get; set; }
    }
}
