//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public byte[] Image { get; set; }
        public string Name { get; set; }
        public string Describe { get; set; }
        public string Maufacture { get; set; }
        public Nullable<float> Price { get; set; }
        public int ID { get; set; }
    }
}
